### ISSUE TITLE
adds fontsize icon to editor but it doesn't work as expected.

### ISSUE THREAD

**Issue by danmarsden** [mediamaisteri/moodle-tiny_fontsize#1]
Hi there, 

I've just tested this and while the use of the drop list under the format -> font-size seems to work, when I click on the fontsize icon in the toolbar it just seems to remove the formatting - I think it would be better to remove the icon from the toolbar or provide a dialogue that allows a user to change the font-size.
[Screencast from 2024-03-18 19-22-35.webm](https://github.com/mediamaisteri/moodle-tiny_fontsize/assets/362798/78e45e32-6de0-4b2f-862e-7e2190f69615)

**Comment by haiksu** [comment]
Thanks for the testing! I'll fix that asap.

**Comment by acquaalta** [comment]
Hi @haiksu,
Do you have an estimate when you would fix the issue and re-submit the plugin for approval in the Moodle Tracker?
This functionality is really needed in TinyMCE, and it would be great if you could let users enjoy it :-)

**Comment by haiksu** [comment]
> Hi @haiksu, Do you have an estimate when you would fix the issue and re-submit the plugin for approval in the Moodle Tracker? This functionality is really needed in TinyMCE, and it would be great if you could let users enjoy it :-)

I'll try to do the fix before my summer holiday, which is starting in the beginning of July. :)

**Comment by fghigini** [comment]
Hi @haiksu ,
Are you planning to work on this plugin soon?
Thank you

**Comment by haiksu** [comment]
Hey all! In the latest commit (https://github.com/mediamaisteri/moodle-tiny_fontsize/commit/112833429de5faf77b24411ef3ce2bba1235999c) I've removed the non-working toolbar icon as it didn't work as intended. Fontsize feature is available in the droplist under format.

Feel free to test again! :)

**Comment by haiksu** [comment]
Plugin has been approved, thanks everyone.
